/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTestsJs {
    @Test
    fun testGreetingJs() {
        val classUnderTest = App()

        assertTrue(
            classUnderTest.greeting.endsWith("[JS]"),
        )
    }
}
