/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTestsJvm {
    @Test
    fun testGreetingJvm() {
        val app = App()

        assertTrue(
            app.greeting.endsWith("[JVM]"),
        )
    }
}
