name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.3

      - name: Check commit messages
        uses: GsActions/commit-message-checker@v2
        with:
          pattern: "^(?!WIP).*$"
          error: "The first line cannot start with WIP"
          excludeDescription: "true"
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & test with Gradle (foundation)
        run: ./gradlew allTest
        working-directory: foundation

      - name: Build & test with Gradle (reactive / push_pull)
        run: ./gradlew allTest -Dimpl=push_pull
        working-directory: reactive

      # Disable the priority_queue tests for now
      
      # - name: Build & test with Gradle (reactive / priority_queue)
      #   run: ./gradlew allTest -Dimpl=priority_queue
      #   working-directory: reactive
